[project]
name = "qwen3-0-6b-quantization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.10.1",
    "torch>=2.8.0",
    "transformers>=4.56.1",
    "pyyaml>=6.0",
    "pydantic>=2.11.9",
]
